TARGET = simulator:clang

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = InternalPhotos
InternalPhotos_FILES = InternalPhotos.xm
InternalPhotos_USE_SUBSTRATE = 0

include $(THEOS_MAKE_PATH)/tweak.mk