TARGET = simulator:clang

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = PreferenceOrganizer2
PreferenceOrganizer2_FILES = PreferenceOrganizer2.xm
PreferenceOrganizer2_USE_SUBSTRATE = 0
PreferenceOrganizer2_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/tweak.mk